# Generated by Django 5.2.5 on 2025-08-24 00:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField()),
                ('negociacao_do_produto', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], default='ABERTO')),
                ('data_leilao', models.DateTimeField(default=datetime.datetime.now)),
                ('dono_do_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='usuarios.usuarios')),
            ],
        ),
    ]
